@startuml bet_oracle
actor User
actor Government
package "Car" {
    card AirBack_App
    card Sensor
}
file Smart_Contract
cloud MachineLearning
cloud CityData

User <-- AirBack_App : feedback
AirBack_App <-- MachineLearning : upcoming pollution
MachineLearning <-- Smart_Contract : pollution
Smart_Contract --> Government : pollution
Government --> User : taxes back
Sensor --> Smart_Contract : pollution
CityData --> MachineLearning : weather,\n traffic lights,\n pollution
@enduml